version: '3.1'

services:
  palbot:
    image: michaefi/palbot:v1
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.10"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    environment:
      CONFIG_SECRETS: /run/secrets/cfg_file
    secrets:
      - cfg_file
    neworks:
      - webnet

secrets:
  cfg_file:
    file: palbot.cfg

networks:
  webnet:
